// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: ports/protos/srv.proto

package hproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddRecipeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title       string                       `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description string                       `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Resources   []*AddRecipeRequest_Resource `protobuf:"bytes,3,rep,name=resources,proto3" json:"resources,omitempty"`
	Tags        []*AddRecipeRequest_Tag      `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *AddRecipeRequest) Reset() {
	*x = AddRecipeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ports_protos_srv_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRecipeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRecipeRequest) ProtoMessage() {}

func (x *AddRecipeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ports_protos_srv_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRecipeRequest.ProtoReflect.Descriptor instead.
func (*AddRecipeRequest) Descriptor() ([]byte, []int) {
	return file_ports_protos_srv_proto_rawDescGZIP(), []int{0}
}

func (x *AddRecipeRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AddRecipeRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AddRecipeRequest) GetResources() []*AddRecipeRequest_Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *AddRecipeRequest) GetTags() []*AddRecipeRequest_Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

type AddRecipeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecipeId string `protobuf:"bytes,1,opt,name=recipeId,proto3" json:"recipeId,omitempty"`
}

func (x *AddRecipeResponse) Reset() {
	*x = AddRecipeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ports_protos_srv_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRecipeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRecipeResponse) ProtoMessage() {}

func (x *AddRecipeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ports_protos_srv_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRecipeResponse.ProtoReflect.Descriptor instead.
func (*AddRecipeResponse) Descriptor() ([]byte, []int) {
	return file_ports_protos_srv_proto_rawDescGZIP(), []int{1}
}

func (x *AddRecipeResponse) GetRecipeId() string {
	if x != nil {
		return x.RecipeId
	}
	return ""
}

type AddRecipeRequest_Resource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind  string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Value string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *AddRecipeRequest_Resource) Reset() {
	*x = AddRecipeRequest_Resource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ports_protos_srv_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRecipeRequest_Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRecipeRequest_Resource) ProtoMessage() {}

func (x *AddRecipeRequest_Resource) ProtoReflect() protoreflect.Message {
	mi := &file_ports_protos_srv_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRecipeRequest_Resource.ProtoReflect.Descriptor instead.
func (*AddRecipeRequest_Resource) Descriptor() ([]byte, []int) {
	return file_ports_protos_srv_proto_rawDescGZIP(), []int{0, 0}
}

func (x *AddRecipeRequest_Resource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddRecipeRequest_Resource) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *AddRecipeRequest_Resource) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type AddRecipeRequest_Tag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *AddRecipeRequest_Tag) Reset() {
	*x = AddRecipeRequest_Tag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ports_protos_srv_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRecipeRequest_Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRecipeRequest_Tag) ProtoMessage() {}

func (x *AddRecipeRequest_Tag) ProtoReflect() protoreflect.Message {
	mi := &file_ports_protos_srv_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRecipeRequest_Tag.ProtoReflect.Descriptor instead.
func (*AddRecipeRequest_Tag) Descriptor() ([]byte, []int) {
	return file_ports_protos_srv_proto_rawDescGZIP(), []int{0, 1}
}

func (x *AddRecipeRequest_Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_ports_protos_srv_proto protoreflect.FileDescriptor

var file_ports_protos_srv_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x73,
	0x72, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x94, 0x02, 0x0a, 0x10, 0x41, 0x64, 0x64,
	0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x38, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x65,
	0x63, 0x69, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x52, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12,
	0x29, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x41, 0x64, 0x64, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x2e, 0x54, 0x61, 0x67, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x1a, 0x48, 0x0a, 0x08, 0x52, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69,
	0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x1a, 0x19, 0x0a, 0x03, 0x54, 0x61, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x2f, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x63, 0x69, 0x70, 0x65, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x63, 0x69, 0x70, 0x65, 0x49, 0x64,
	0x32, 0x3e, 0x0a, 0x06, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x12, 0x34, 0x0a, 0x09, 0x41, 0x64,
	0x64, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x12, 0x11, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x65, 0x63,
	0x69, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x41, 0x64, 0x64,
	0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x38,
	0x36, 0x73, 0x6f, 0x66, 0x74, 0x2f, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x79, 0x72, 0x6f, 0x2d,
	0x72, 0x65, 0x63, 0x69, 0x70, 0x65, 0x73, 0x3b, 0x68, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ports_protos_srv_proto_rawDescOnce sync.Once
	file_ports_protos_srv_proto_rawDescData = file_ports_protos_srv_proto_rawDesc
)

func file_ports_protos_srv_proto_rawDescGZIP() []byte {
	file_ports_protos_srv_proto_rawDescOnce.Do(func() {
		file_ports_protos_srv_proto_rawDescData = protoimpl.X.CompressGZIP(file_ports_protos_srv_proto_rawDescData)
	})
	return file_ports_protos_srv_proto_rawDescData
}

var file_ports_protos_srv_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ports_protos_srv_proto_goTypes = []interface{}{
	(*AddRecipeRequest)(nil),          // 0: AddRecipeRequest
	(*AddRecipeResponse)(nil),         // 1: AddRecipeResponse
	(*AddRecipeRequest_Resource)(nil), // 2: AddRecipeRequest.Resource
	(*AddRecipeRequest_Tag)(nil),      // 3: AddRecipeRequest.Tag
}
var file_ports_protos_srv_proto_depIdxs = []int32{
	2, // 0: AddRecipeRequest.resources:type_name -> AddRecipeRequest.Resource
	3, // 1: AddRecipeRequest.tags:type_name -> AddRecipeRequest.Tag
	0, // 2: Recipe.CreateRecipe:input_type -> AddRecipeRequest
	1, // 3: Recipe.CreateRecipe:output_type -> AddRecipeResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ports_protos_srv_proto_init() }
func file_ports_protos_srv_proto_init() {
	if File_ports_protos_srv_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ports_protos_srv_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRecipeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ports_protos_srv_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRecipeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ports_protos_srv_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRecipeRequest_Resource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ports_protos_srv_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRecipeRequest_Tag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ports_protos_srv_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ports_protos_srv_proto_goTypes,
		DependencyIndexes: file_ports_protos_srv_proto_depIdxs,
		MessageInfos:      file_ports_protos_srv_proto_msgTypes,
	}.Build()
	File_ports_protos_srv_proto = out.File
	file_ports_protos_srv_proto_rawDesc = nil
	file_ports_protos_srv_proto_goTypes = nil
	file_ports_protos_srv_proto_depIdxs = nil
}
