// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: ports/protos/srv.proto

package hproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RemoveResourceFromRecipeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecipeId   string `protobuf:"bytes,1,opt,name=recipeId,proto3" json:"recipeId,omitempty"`
	ResourceId string `protobuf:"bytes,2,opt,name=resourceId,proto3" json:"resourceId,omitempty"`
}

func (x *RemoveResourceFromRecipeRequest) Reset() {
	*x = RemoveResourceFromRecipeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ports_protos_srv_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveResourceFromRecipeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveResourceFromRecipeRequest) ProtoMessage() {}

func (x *RemoveResourceFromRecipeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ports_protos_srv_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveResourceFromRecipeRequest.ProtoReflect.Descriptor instead.
func (*RemoveResourceFromRecipeRequest) Descriptor() ([]byte, []int) {
	return file_ports_protos_srv_proto_rawDescGZIP(), []int{0}
}

func (x *RemoveResourceFromRecipeRequest) GetRecipeId() string {
	if x != nil {
		return x.RecipeId
	}
	return ""
}

func (x *RemoveResourceFromRecipeRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

type RemoveRecipeFromResourceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RemoveRecipeFromResourceResponse) Reset() {
	*x = RemoveRecipeFromResourceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ports_protos_srv_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveRecipeFromResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRecipeFromResourceResponse) ProtoMessage() {}

func (x *RemoveRecipeFromResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ports_protos_srv_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRecipeFromResourceResponse.ProtoReflect.Descriptor instead.
func (*RemoveRecipeFromResourceResponse) Descriptor() ([]byte, []int) {
	return file_ports_protos_srv_proto_rawDescGZIP(), []int{1}
}

type Recipe struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecipeId    string             `protobuf:"bytes,1,opt,name=recipeId,proto3" json:"recipeId,omitempty"`
	Title       string             `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description string             `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Resources   []*Recipe_Resource `protobuf:"bytes,4,rep,name=resources,proto3" json:"resources,omitempty"`
	Tags        []*Recipe_Tag      `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *Recipe) Reset() {
	*x = Recipe{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ports_protos_srv_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Recipe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recipe) ProtoMessage() {}

func (x *Recipe) ProtoReflect() protoreflect.Message {
	mi := &file_ports_protos_srv_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recipe.ProtoReflect.Descriptor instead.
func (*Recipe) Descriptor() ([]byte, []int) {
	return file_ports_protos_srv_proto_rawDescGZIP(), []int{2}
}

func (x *Recipe) GetRecipeId() string {
	if x != nil {
		return x.RecipeId
	}
	return ""
}

func (x *Recipe) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Recipe) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Recipe) GetResources() []*Recipe_Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *Recipe) GetTags() []*Recipe_Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

type CreateRecipeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title       string                          `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description string                          `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Resources   []*CreateRecipeRequest_Resource `protobuf:"bytes,3,rep,name=resources,proto3" json:"resources,omitempty"`
	Tags        []*CreateRecipeRequest_Tag      `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *CreateRecipeRequest) Reset() {
	*x = CreateRecipeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ports_protos_srv_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRecipeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRecipeRequest) ProtoMessage() {}

func (x *CreateRecipeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ports_protos_srv_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRecipeRequest.ProtoReflect.Descriptor instead.
func (*CreateRecipeRequest) Descriptor() ([]byte, []int) {
	return file_ports_protos_srv_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRecipeRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateRecipeRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateRecipeRequest) GetResources() []*CreateRecipeRequest_Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *CreateRecipeRequest) GetTags() []*CreateRecipeRequest_Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

type CreateRecipeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecipeId string `protobuf:"bytes,1,opt,name=recipeId,proto3" json:"recipeId,omitempty"`
}

func (x *CreateRecipeResponse) Reset() {
	*x = CreateRecipeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ports_protos_srv_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRecipeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRecipeResponse) ProtoMessage() {}

func (x *CreateRecipeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ports_protos_srv_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRecipeResponse.ProtoReflect.Descriptor instead.
func (*CreateRecipeResponse) Descriptor() ([]byte, []int) {
	return file_ports_protos_srv_proto_rawDescGZIP(), []int{4}
}

func (x *CreateRecipeResponse) GetRecipeId() string {
	if x != nil {
		return x.RecipeId
	}
	return ""
}

type ListRecipeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title       string                        `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description string                        `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Resources   []*ListRecipeRequest_Resource `protobuf:"bytes,3,rep,name=resources,proto3" json:"resources,omitempty"`
	Tags        []*ListRecipeRequest_Tag      `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *ListRecipeRequest) Reset() {
	*x = ListRecipeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ports_protos_srv_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRecipeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecipeRequest) ProtoMessage() {}

func (x *ListRecipeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ports_protos_srv_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecipeRequest.ProtoReflect.Descriptor instead.
func (*ListRecipeRequest) Descriptor() ([]byte, []int) {
	return file_ports_protos_srv_proto_rawDescGZIP(), []int{5}
}

func (x *ListRecipeRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ListRecipeRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ListRecipeRequest) GetResources() []*ListRecipeRequest_Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *ListRecipeRequest) GetTags() []*ListRecipeRequest_Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

type ListRecipeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Recipes []*Recipe `protobuf:"bytes,1,rep,name=recipes,proto3" json:"recipes,omitempty"`
}

func (x *ListRecipeResponse) Reset() {
	*x = ListRecipeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ports_protos_srv_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRecipeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecipeResponse) ProtoMessage() {}

func (x *ListRecipeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ports_protos_srv_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecipeResponse.ProtoReflect.Descriptor instead.
func (*ListRecipeResponse) Descriptor() ([]byte, []int) {
	return file_ports_protos_srv_proto_rawDescGZIP(), []int{6}
}

func (x *ListRecipeResponse) GetRecipes() []*Recipe {
	if x != nil {
		return x.Recipes
	}
	return nil
}

type FindRecipesByNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *FindRecipesByNameRequest) Reset() {
	*x = FindRecipesByNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ports_protos_srv_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindRecipesByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRecipesByNameRequest) ProtoMessage() {}

func (x *FindRecipesByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ports_protos_srv_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRecipesByNameRequest.ProtoReflect.Descriptor instead.
func (*FindRecipesByNameRequest) Descriptor() ([]byte, []int) {
	return file_ports_protos_srv_proto_rawDescGZIP(), []int{7}
}

func (x *FindRecipesByNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type FindRecipesByNameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Recipes []*Recipe `protobuf:"bytes,1,rep,name=recipes,proto3" json:"recipes,omitempty"`
}

func (x *FindRecipesByNameResponse) Reset() {
	*x = FindRecipesByNameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ports_protos_srv_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindRecipesByNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRecipesByNameResponse) ProtoMessage() {}

func (x *FindRecipesByNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ports_protos_srv_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRecipesByNameResponse.ProtoReflect.Descriptor instead.
func (*FindRecipesByNameResponse) Descriptor() ([]byte, []int) {
	return file_ports_protos_srv_proto_rawDescGZIP(), []int{8}
}

func (x *FindRecipesByNameResponse) GetRecipes() []*Recipe {
	if x != nil {
		return x.Recipes
	}
	return nil
}

type GetRecipeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecipeId string `protobuf:"bytes,1,opt,name=recipeId,proto3" json:"recipeId,omitempty"`
}

func (x *GetRecipeRequest) Reset() {
	*x = GetRecipeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ports_protos_srv_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRecipeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecipeRequest) ProtoMessage() {}

func (x *GetRecipeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ports_protos_srv_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecipeRequest.ProtoReflect.Descriptor instead.
func (*GetRecipeRequest) Descriptor() ([]byte, []int) {
	return file_ports_protos_srv_proto_rawDescGZIP(), []int{9}
}

func (x *GetRecipeRequest) GetRecipeId() string {
	if x != nil {
		return x.RecipeId
	}
	return ""
}

type GetRecipeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Recipe *Recipe `protobuf:"bytes,1,opt,name=recipe,proto3" json:"recipe,omitempty"`
}

func (x *GetRecipeResponse) Reset() {
	*x = GetRecipeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ports_protos_srv_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRecipeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecipeResponse) ProtoMessage() {}

func (x *GetRecipeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ports_protos_srv_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecipeResponse.ProtoReflect.Descriptor instead.
func (*GetRecipeResponse) Descriptor() ([]byte, []int) {
	return file_ports_protos_srv_proto_rawDescGZIP(), []int{10}
}

func (x *GetRecipeResponse) GetRecipe() *Recipe {
	if x != nil {
		return x.Recipe
	}
	return nil
}

type FindRecipesByTagsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tags []string `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *FindRecipesByTagsRequest) Reset() {
	*x = FindRecipesByTagsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ports_protos_srv_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindRecipesByTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRecipesByTagsRequest) ProtoMessage() {}

func (x *FindRecipesByTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ports_protos_srv_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRecipesByTagsRequest.ProtoReflect.Descriptor instead.
func (*FindRecipesByTagsRequest) Descriptor() ([]byte, []int) {
	return file_ports_protos_srv_proto_rawDescGZIP(), []int{11}
}

func (x *FindRecipesByTagsRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type FindRecipesByTagsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Recipes []*Recipe `protobuf:"bytes,1,rep,name=recipes,proto3" json:"recipes,omitempty"`
}

func (x *FindRecipesByTagsResponse) Reset() {
	*x = FindRecipesByTagsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ports_protos_srv_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindRecipesByTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRecipesByTagsResponse) ProtoMessage() {}

func (x *FindRecipesByTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ports_protos_srv_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRecipesByTagsResponse.ProtoReflect.Descriptor instead.
func (*FindRecipesByTagsResponse) Descriptor() ([]byte, []int) {
	return file_ports_protos_srv_proto_rawDescGZIP(), []int{12}
}

func (x *FindRecipesByTagsResponse) GetRecipes() []*Recipe {
	if x != nil {
		return x.Recipes
	}
	return nil
}

type UpdateRecipeTitleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecipeId string `protobuf:"bytes,1,opt,name=recipeId,proto3" json:"recipeId,omitempty"`
	Title    string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
}

func (x *UpdateRecipeTitleRequest) Reset() {
	*x = UpdateRecipeTitleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ports_protos_srv_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRecipeTitleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRecipeTitleRequest) ProtoMessage() {}

func (x *UpdateRecipeTitleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ports_protos_srv_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRecipeTitleRequest.ProtoReflect.Descriptor instead.
func (*UpdateRecipeTitleRequest) Descriptor() ([]byte, []int) {
	return file_ports_protos_srv_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateRecipeTitleRequest) GetRecipeId() string {
	if x != nil {
		return x.RecipeId
	}
	return ""
}

func (x *UpdateRecipeTitleRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type UpdateRecipeTitleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateRecipeTitleResponse) Reset() {
	*x = UpdateRecipeTitleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ports_protos_srv_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRecipeTitleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRecipeTitleResponse) ProtoMessage() {}

func (x *UpdateRecipeTitleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ports_protos_srv_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRecipeTitleResponse.ProtoReflect.Descriptor instead.
func (*UpdateRecipeTitleResponse) Descriptor() ([]byte, []int) {
	return file_ports_protos_srv_proto_rawDescGZIP(), []int{14}
}

type UpdateRecipeDescriptionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecipeId    string `protobuf:"bytes,1,opt,name=recipeId,proto3" json:"recipeId,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *UpdateRecipeDescriptionRequest) Reset() {
	*x = UpdateRecipeDescriptionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ports_protos_srv_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRecipeDescriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRecipeDescriptionRequest) ProtoMessage() {}

func (x *UpdateRecipeDescriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ports_protos_srv_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRecipeDescriptionRequest.ProtoReflect.Descriptor instead.
func (*UpdateRecipeDescriptionRequest) Descriptor() ([]byte, []int) {
	return file_ports_protos_srv_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateRecipeDescriptionRequest) GetRecipeId() string {
	if x != nil {
		return x.RecipeId
	}
	return ""
}

func (x *UpdateRecipeDescriptionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateRecipeDescriptionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateRecipeDescriptionResponse) Reset() {
	*x = UpdateRecipeDescriptionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ports_protos_srv_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRecipeDescriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRecipeDescriptionResponse) ProtoMessage() {}

func (x *UpdateRecipeDescriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ports_protos_srv_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRecipeDescriptionResponse.ProtoReflect.Descriptor instead.
func (*UpdateRecipeDescriptionResponse) Descriptor() ([]byte, []int) {
	return file_ports_protos_srv_proto_rawDescGZIP(), []int{16}
}

type DeleteRecipeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecipeId string `protobuf:"bytes,1,opt,name=recipeId,proto3" json:"recipeId,omitempty"`
}

func (x *DeleteRecipeRequest) Reset() {
	*x = DeleteRecipeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ports_protos_srv_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRecipeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRecipeRequest) ProtoMessage() {}

func (x *DeleteRecipeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ports_protos_srv_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRecipeRequest.ProtoReflect.Descriptor instead.
func (*DeleteRecipeRequest) Descriptor() ([]byte, []int) {
	return file_ports_protos_srv_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteRecipeRequest) GetRecipeId() string {
	if x != nil {
		return x.RecipeId
	}
	return ""
}

type DeleteRecipeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteRecipeResponse) Reset() {
	*x = DeleteRecipeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ports_protos_srv_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRecipeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRecipeResponse) ProtoMessage() {}

func (x *DeleteRecipeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ports_protos_srv_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRecipeResponse.ProtoReflect.Descriptor instead.
func (*DeleteRecipeResponse) Descriptor() ([]byte, []int) {
	return file_ports_protos_srv_proto_rawDescGZIP(), []int{18}
}

type AddRecipeResourceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecipeId string `protobuf:"bytes,1,opt,name=recipeId,proto3" json:"recipeId,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Kind     string `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Value    string `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *AddRecipeResourceRequest) Reset() {
	*x = AddRecipeResourceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ports_protos_srv_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRecipeResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRecipeResourceRequest) ProtoMessage() {}

func (x *AddRecipeResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ports_protos_srv_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRecipeResourceRequest.ProtoReflect.Descriptor instead.
func (*AddRecipeResourceRequest) Descriptor() ([]byte, []int) {
	return file_ports_protos_srv_proto_rawDescGZIP(), []int{19}
}

func (x *AddRecipeResourceRequest) GetRecipeId() string {
	if x != nil {
		return x.RecipeId
	}
	return ""
}

func (x *AddRecipeResourceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddRecipeResourceRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *AddRecipeResourceRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type AddRecipeResourceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddRecipeResourceResponse) Reset() {
	*x = AddRecipeResourceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ports_protos_srv_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRecipeResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRecipeResourceResponse) ProtoMessage() {}

func (x *AddRecipeResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ports_protos_srv_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRecipeResourceResponse.ProtoReflect.Descriptor instead.
func (*AddRecipeResourceResponse) Descriptor() ([]byte, []int) {
	return file_ports_protos_srv_proto_rawDescGZIP(), []int{20}
}

type CreateTagRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CreateTagRequest) Reset() {
	*x = CreateTagRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ports_protos_srv_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTagRequest) ProtoMessage() {}

func (x *CreateTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ports_protos_srv_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTagRequest.ProtoReflect.Descriptor instead.
func (*CreateTagRequest) Descriptor() ([]byte, []int) {
	return file_ports_protos_srv_proto_rawDescGZIP(), []int{21}
}

func (x *CreateTagRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateTagResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TagId string `protobuf:"bytes,1,opt,name=tagId,proto3" json:"tagId,omitempty"`
}

func (x *CreateTagResponse) Reset() {
	*x = CreateTagResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ports_protos_srv_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTagResponse) ProtoMessage() {}

func (x *CreateTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ports_protos_srv_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTagResponse.ProtoReflect.Descriptor instead.
func (*CreateTagResponse) Descriptor() ([]byte, []int) {
	return file_ports_protos_srv_proto_rawDescGZIP(), []int{22}
}

func (x *CreateTagResponse) GetTagId() string {
	if x != nil {
		return x.TagId
	}
	return ""
}

type AddTagToRecipeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecipeId     string `protobuf:"bytes,1,opt,name=recipeId,proto3" json:"recipeId,omitempty"`
	TagId        string `protobuf:"bytes,2,opt,name=tagId,proto3" json:"tagId,omitempty"`
	TagName      string `protobuf:"bytes,3,opt,name=tagName,proto3" json:"tagName,omitempty"`
	CreateNewTag bool   `protobuf:"varint,4,opt,name=createNewTag,proto3" json:"createNewTag,omitempty"`
}

func (x *AddTagToRecipeRequest) Reset() {
	*x = AddTagToRecipeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ports_protos_srv_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddTagToRecipeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTagToRecipeRequest) ProtoMessage() {}

func (x *AddTagToRecipeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ports_protos_srv_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTagToRecipeRequest.ProtoReflect.Descriptor instead.
func (*AddTagToRecipeRequest) Descriptor() ([]byte, []int) {
	return file_ports_protos_srv_proto_rawDescGZIP(), []int{23}
}

func (x *AddTagToRecipeRequest) GetRecipeId() string {
	if x != nil {
		return x.RecipeId
	}
	return ""
}

func (x *AddTagToRecipeRequest) GetTagId() string {
	if x != nil {
		return x.TagId
	}
	return ""
}

func (x *AddTagToRecipeRequest) GetTagName() string {
	if x != nil {
		return x.TagName
	}
	return ""
}

func (x *AddTagToRecipeRequest) GetCreateNewTag() bool {
	if x != nil {
		return x.CreateNewTag
	}
	return false
}

type AddTagToRecipeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddTagToRecipeResponse) Reset() {
	*x = AddTagToRecipeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ports_protos_srv_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddTagToRecipeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTagToRecipeResponse) ProtoMessage() {}

func (x *AddTagToRecipeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ports_protos_srv_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTagToRecipeResponse.ProtoReflect.Descriptor instead.
func (*AddTagToRecipeResponse) Descriptor() ([]byte, []int) {
	return file_ports_protos_srv_proto_rawDescGZIP(), []int{24}
}

type RemoveTagFromRecipeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecipeId string `protobuf:"bytes,1,opt,name=recipeId,proto3" json:"recipeId,omitempty"`
	TagId    string `protobuf:"bytes,2,opt,name=tagId,proto3" json:"tagId,omitempty"`
	TagName  string `protobuf:"bytes,3,opt,name=tagName,proto3" json:"tagName,omitempty"`
}

func (x *RemoveTagFromRecipeRequest) Reset() {
	*x = RemoveTagFromRecipeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ports_protos_srv_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveTagFromRecipeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTagFromRecipeRequest) ProtoMessage() {}

func (x *RemoveTagFromRecipeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ports_protos_srv_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTagFromRecipeRequest.ProtoReflect.Descriptor instead.
func (*RemoveTagFromRecipeRequest) Descriptor() ([]byte, []int) {
	return file_ports_protos_srv_proto_rawDescGZIP(), []int{25}
}

func (x *RemoveTagFromRecipeRequest) GetRecipeId() string {
	if x != nil {
		return x.RecipeId
	}
	return ""
}

func (x *RemoveTagFromRecipeRequest) GetTagId() string {
	if x != nil {
		return x.TagId
	}
	return ""
}

func (x *RemoveTagFromRecipeRequest) GetTagName() string {
	if x != nil {
		return x.TagName
	}
	return ""
}

type RemoveTagFromRecipeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RemoveTagFromRecipeResponse) Reset() {
	*x = RemoveTagFromRecipeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ports_protos_srv_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveTagFromRecipeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTagFromRecipeResponse) ProtoMessage() {}

func (x *RemoveTagFromRecipeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ports_protos_srv_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTagFromRecipeResponse.ProtoReflect.Descriptor instead.
func (*RemoveTagFromRecipeResponse) Descriptor() ([]byte, []int) {
	return file_ports_protos_srv_proto_rawDescGZIP(), []int{26}
}

type Recipe_Resource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResourceId string `protobuf:"bytes,1,opt,name=resourceId,proto3" json:"resourceId,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Kind       string `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Value      string `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Recipe_Resource) Reset() {
	*x = Recipe_Resource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ports_protos_srv_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Recipe_Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recipe_Resource) ProtoMessage() {}

func (x *Recipe_Resource) ProtoReflect() protoreflect.Message {
	mi := &file_ports_protos_srv_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recipe_Resource.ProtoReflect.Descriptor instead.
func (*Recipe_Resource) Descriptor() ([]byte, []int) {
	return file_ports_protos_srv_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Recipe_Resource) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *Recipe_Resource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Recipe_Resource) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Recipe_Resource) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Recipe_Tag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Recipe_Tag) Reset() {
	*x = Recipe_Tag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ports_protos_srv_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Recipe_Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recipe_Tag) ProtoMessage() {}

func (x *Recipe_Tag) ProtoReflect() protoreflect.Message {
	mi := &file_ports_protos_srv_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recipe_Tag.ProtoReflect.Descriptor instead.
func (*Recipe_Tag) Descriptor() ([]byte, []int) {
	return file_ports_protos_srv_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Recipe_Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateRecipeRequest_Resource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind  string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Value string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *CreateRecipeRequest_Resource) Reset() {
	*x = CreateRecipeRequest_Resource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ports_protos_srv_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRecipeRequest_Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRecipeRequest_Resource) ProtoMessage() {}

func (x *CreateRecipeRequest_Resource) ProtoReflect() protoreflect.Message {
	mi := &file_ports_protos_srv_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRecipeRequest_Resource.ProtoReflect.Descriptor instead.
func (*CreateRecipeRequest_Resource) Descriptor() ([]byte, []int) {
	return file_ports_protos_srv_proto_rawDescGZIP(), []int{3, 0}
}

func (x *CreateRecipeRequest_Resource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRecipeRequest_Resource) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *CreateRecipeRequest_Resource) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type CreateRecipeRequest_Tag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CreateRecipeRequest_Tag) Reset() {
	*x = CreateRecipeRequest_Tag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ports_protos_srv_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRecipeRequest_Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRecipeRequest_Tag) ProtoMessage() {}

func (x *CreateRecipeRequest_Tag) ProtoReflect() protoreflect.Message {
	mi := &file_ports_protos_srv_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRecipeRequest_Tag.ProtoReflect.Descriptor instead.
func (*CreateRecipeRequest_Tag) Descriptor() ([]byte, []int) {
	return file_ports_protos_srv_proto_rawDescGZIP(), []int{3, 1}
}

func (x *CreateRecipeRequest_Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListRecipeRequest_Resource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind  string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Value string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ListRecipeRequest_Resource) Reset() {
	*x = ListRecipeRequest_Resource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ports_protos_srv_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRecipeRequest_Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecipeRequest_Resource) ProtoMessage() {}

func (x *ListRecipeRequest_Resource) ProtoReflect() protoreflect.Message {
	mi := &file_ports_protos_srv_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecipeRequest_Resource.ProtoReflect.Descriptor instead.
func (*ListRecipeRequest_Resource) Descriptor() ([]byte, []int) {
	return file_ports_protos_srv_proto_rawDescGZIP(), []int{5, 0}
}

func (x *ListRecipeRequest_Resource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListRecipeRequest_Resource) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ListRecipeRequest_Resource) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ListRecipeRequest_Tag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ListRecipeRequest_Tag) Reset() {
	*x = ListRecipeRequest_Tag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ports_protos_srv_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRecipeRequest_Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecipeRequest_Tag) ProtoMessage() {}

func (x *ListRecipeRequest_Tag) ProtoReflect() protoreflect.Message {
	mi := &file_ports_protos_srv_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecipeRequest_Tag.ProtoReflect.Descriptor instead.
func (*ListRecipeRequest_Tag) Descriptor() ([]byte, []int) {
	return file_ports_protos_srv_proto_rawDescGZIP(), []int{5, 1}
}

func (x *ListRecipeRequest_Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_ports_protos_srv_proto protoreflect.FileDescriptor

var file_ports_protos_srv_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x73,
	0x72, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5d, 0x0a, 0x1f, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x52, 0x65,
	0x63, 0x69, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x72,
	0x65, 0x63, 0x69, 0x70, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72,
	0x65, 0x63, 0x69, 0x70, 0x65, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x22, 0x22, 0x0a, 0x20, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xb2, 0x02, 0x0a, 0x06,
	0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x63, 0x69, 0x70, 0x65,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x63, 0x69, 0x70, 0x65,
	0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2e, 0x0a, 0x09, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52,
	0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x1f, 0x0a, 0x04, 0x74, 0x61,
	0x67, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x52, 0x65, 0x63, 0x69, 0x70,
	0x65, 0x2e, 0x54, 0x61, 0x67, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x1a, 0x68, 0x0a, 0x08, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6b,
	0x69, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0x19, 0x0a, 0x03, 0x54, 0x61, 0x67, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x9d, 0x02, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x69, 0x70,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x3b, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x69,
	0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x52, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x2c, 0x0a,
	0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2e, 0x54, 0x61, 0x67, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x1a, 0x48, 0x0a, 0x08, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6b,
	0x69, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0x19, 0x0a, 0x03, 0x54, 0x61, 0x67, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x32, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x63, 0x69,
	0x70, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x63, 0x69,
	0x70, 0x65, 0x49, 0x64, 0x22, 0x97, 0x02, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x63,
	0x69, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x39, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x69,
	0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x52, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x2a, 0x0a,
	0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e,
	0x54, 0x61, 0x67, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x1a, 0x48, 0x0a, 0x08, 0x52, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x1a, 0x19, 0x0a, 0x03, 0x54, 0x61, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x37,
	0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x07, 0x72, 0x65, 0x63, 0x69, 0x70, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x52, 0x07,
	0x72, 0x65, 0x63, 0x69, 0x70, 0x65, 0x73, 0x22, 0x2e, 0x0a, 0x18, 0x46, 0x69, 0x6e, 0x64, 0x52,
	0x65, 0x63, 0x69, 0x70, 0x65, 0x73, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3e, 0x0a, 0x19, 0x46, 0x69, 0x6e, 0x64, 0x52,
	0x65, 0x63, 0x69, 0x70, 0x65, 0x73, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x07, 0x72, 0x65, 0x63, 0x69, 0x70, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x52, 0x07,
	0x72, 0x65, 0x63, 0x69, 0x70, 0x65, 0x73, 0x22, 0x2e, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x63, 0x69, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x72,
	0x65, 0x63, 0x69, 0x70, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72,
	0x65, 0x63, 0x69, 0x70, 0x65, 0x49, 0x64, 0x22, 0x34, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x63, 0x69, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x06,
	0x72, 0x65, 0x63, 0x69, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x52,
	0x65, 0x63, 0x69, 0x70, 0x65, 0x52, 0x06, 0x72, 0x65, 0x63, 0x69, 0x70, 0x65, 0x22, 0x2e, 0x0a,
	0x18, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x73, 0x42, 0x79, 0x54, 0x61,
	0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x22, 0x3e, 0x0a,
	0x19, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x73, 0x42, 0x79, 0x54, 0x61,
	0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x07, 0x72, 0x65,
	0x63, 0x69, 0x70, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x52, 0x65,
	0x63, 0x69, 0x70, 0x65, 0x52, 0x07, 0x72, 0x65, 0x63, 0x69, 0x70, 0x65, 0x73, 0x22, 0x4c, 0x0a,
	0x18, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x54, 0x69, 0x74,
	0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x63,
	0x69, 0x70, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x63,
	0x69, 0x70, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x22, 0x1b, 0x0a, 0x19, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x54, 0x69, 0x74, 0x6c, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x5e, 0x0a, 0x1e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65,
	0x63, 0x69, 0x70, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65,
	0x63, 0x69, 0x70, 0x65, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x21, 0x0a, 0x1f, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x31, 0x0a, 0x13, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x63, 0x69, 0x70, 0x65, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x63, 0x69, 0x70, 0x65, 0x49, 0x64, 0x22, 0x16,
	0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x74, 0x0a, 0x18, 0x41, 0x64, 0x64, 0x52, 0x65, 0x63,
	0x69, 0x70, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x63, 0x69, 0x70, 0x65, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x63, 0x69, 0x70, 0x65, 0x49, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x1b, 0x0a, 0x19,
	0x41, 0x64, 0x64, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x26, 0x0a, 0x10, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x29, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x67, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x61, 0x67, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x61, 0x67, 0x49, 0x64, 0x22, 0x87, 0x01, 0x0a,
	0x15, 0x41, 0x64, 0x64, 0x54, 0x61, 0x67, 0x54, 0x6f, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x63, 0x69, 0x70, 0x65,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x63, 0x69, 0x70, 0x65,
	0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x61, 0x67, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x61, 0x67, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x61, 0x67, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x61, 0x67, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x77, 0x54,
	0x61, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x4e, 0x65, 0x77, 0x54, 0x61, 0x67, 0x22, 0x18, 0x0a, 0x16, 0x41, 0x64, 0x64, 0x54, 0x61, 0x67,
	0x54, 0x6f, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x68, 0x0a, 0x1a, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x54, 0x61, 0x67, 0x46, 0x72, 0x6f,
	0x6d, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x72, 0x65, 0x63, 0x69, 0x70, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x72, 0x65, 0x63, 0x69, 0x70, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x61,
	0x67, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x61, 0x67, 0x49, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x74, 0x61, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x74, 0x61, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x1d, 0x0a, 0x1b, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x54, 0x61, 0x67, 0x46, 0x72, 0x6f, 0x6d, 0x52, 0x65, 0x63, 0x69, 0x70,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xc2, 0x07, 0x0a, 0x09, 0x52, 0x65,
	0x63, 0x69, 0x70, 0x65, 0x53, 0x76, 0x63, 0x12, 0x37, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x63, 0x69, 0x70, 0x65, 0x12, 0x12, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x69,
	0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x4c, 0x0a, 0x11, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x73, 0x42,
	0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x63, 0x69,
	0x70, 0x65, 0x73, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1a, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x73, 0x42, 0x79,
	0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x34,
	0x0a, 0x09, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x12, 0x11, 0x2e, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12,
	0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x63, 0x69, 0x70, 0x65, 0x12, 0x14, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63,
	0x69, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x11, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x63, 0x69, 0x70,
	0x65, 0x73, 0x42, 0x79, 0x54, 0x61, 0x67, 0x73, 0x12, 0x19, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x52,
	0x65, 0x63, 0x69, 0x70, 0x65, 0x73, 0x42, 0x79, 0x54, 0x61, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65,
	0x73, 0x42, 0x79, 0x54, 0x61, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x4c, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x69, 0x70,
	0x65, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x19, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x63, 0x69, 0x70, 0x65, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1a, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65,
	0x54, 0x69, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x5e, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x44,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x3d, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x12,
	0x14, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65,
	0x63, 0x69, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x61,
	0x0a, 0x18, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x46, 0x72,
	0x6f, 0x6d, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x20, 0x2e, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x52,
	0x65, 0x63, 0x69, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x4c, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x52, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x19, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x65, 0x63, 0x69,
	0x70, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1a, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x52, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x34, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x67, 0x12, 0x11, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x12, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x54, 0x61, 0x67, 0x54,
	0x6f, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x12, 0x16, 0x2e, 0x41, 0x64, 0x64, 0x54, 0x61, 0x67,
	0x54, 0x6f, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x17, 0x2e, 0x41, 0x64, 0x64, 0x54, 0x61, 0x67, 0x54, 0x6f, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x52, 0x0a, 0x13, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x54, 0x61, 0x67, 0x46, 0x72, 0x6f, 0x6d, 0x52, 0x65, 0x63, 0x69, 0x70,
	0x65, 0x12, 0x1b, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x54, 0x61, 0x67, 0x46, 0x72, 0x6f,
	0x6d, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c,
	0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x54, 0x61, 0x67, 0x46, 0x72, 0x6f, 0x6d, 0x52, 0x65,
	0x63, 0x69, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2c,
	0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x38, 0x36, 0x73,
	0x6f, 0x66, 0x74, 0x2f, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x79, 0x72, 0x6f, 0x2d, 0x72, 0x65,
	0x63, 0x69, 0x70, 0x65, 0x73, 0x3b, 0x68, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ports_protos_srv_proto_rawDescOnce sync.Once
	file_ports_protos_srv_proto_rawDescData = file_ports_protos_srv_proto_rawDesc
)

func file_ports_protos_srv_proto_rawDescGZIP() []byte {
	file_ports_protos_srv_proto_rawDescOnce.Do(func() {
		file_ports_protos_srv_proto_rawDescData = protoimpl.X.CompressGZIP(file_ports_protos_srv_proto_rawDescData)
	})
	return file_ports_protos_srv_proto_rawDescData
}

var file_ports_protos_srv_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_ports_protos_srv_proto_goTypes = []interface{}{
	(*RemoveResourceFromRecipeRequest)(nil),  // 0: RemoveResourceFromRecipeRequest
	(*RemoveRecipeFromResourceResponse)(nil), // 1: RemoveRecipeFromResourceResponse
	(*Recipe)(nil),                           // 2: Recipe
	(*CreateRecipeRequest)(nil),              // 3: CreateRecipeRequest
	(*CreateRecipeResponse)(nil),             // 4: CreateRecipeResponse
	(*ListRecipeRequest)(nil),                // 5: ListRecipeRequest
	(*ListRecipeResponse)(nil),               // 6: ListRecipeResponse
	(*FindRecipesByNameRequest)(nil),         // 7: FindRecipesByNameRequest
	(*FindRecipesByNameResponse)(nil),        // 8: FindRecipesByNameResponse
	(*GetRecipeRequest)(nil),                 // 9: GetRecipeRequest
	(*GetRecipeResponse)(nil),                // 10: GetRecipeResponse
	(*FindRecipesByTagsRequest)(nil),         // 11: FindRecipesByTagsRequest
	(*FindRecipesByTagsResponse)(nil),        // 12: FindRecipesByTagsResponse
	(*UpdateRecipeTitleRequest)(nil),         // 13: UpdateRecipeTitleRequest
	(*UpdateRecipeTitleResponse)(nil),        // 14: UpdateRecipeTitleResponse
	(*UpdateRecipeDescriptionRequest)(nil),   // 15: UpdateRecipeDescriptionRequest
	(*UpdateRecipeDescriptionResponse)(nil),  // 16: UpdateRecipeDescriptionResponse
	(*DeleteRecipeRequest)(nil),              // 17: DeleteRecipeRequest
	(*DeleteRecipeResponse)(nil),             // 18: DeleteRecipeResponse
	(*AddRecipeResourceRequest)(nil),         // 19: AddRecipeResourceRequest
	(*AddRecipeResourceResponse)(nil),        // 20: AddRecipeResourceResponse
	(*CreateTagRequest)(nil),                 // 21: CreateTagRequest
	(*CreateTagResponse)(nil),                // 22: CreateTagResponse
	(*AddTagToRecipeRequest)(nil),            // 23: AddTagToRecipeRequest
	(*AddTagToRecipeResponse)(nil),           // 24: AddTagToRecipeResponse
	(*RemoveTagFromRecipeRequest)(nil),       // 25: RemoveTagFromRecipeRequest
	(*RemoveTagFromRecipeResponse)(nil),      // 26: RemoveTagFromRecipeResponse
	(*Recipe_Resource)(nil),                  // 27: Recipe.Resource
	(*Recipe_Tag)(nil),                       // 28: Recipe.Tag
	(*CreateRecipeRequest_Resource)(nil),     // 29: CreateRecipeRequest.Resource
	(*CreateRecipeRequest_Tag)(nil),          // 30: CreateRecipeRequest.Tag
	(*ListRecipeRequest_Resource)(nil),       // 31: ListRecipeRequest.Resource
	(*ListRecipeRequest_Tag)(nil),            // 32: ListRecipeRequest.Tag
}
var file_ports_protos_srv_proto_depIdxs = []int32{
	27, // 0: Recipe.resources:type_name -> Recipe.Resource
	28, // 1: Recipe.tags:type_name -> Recipe.Tag
	29, // 2: CreateRecipeRequest.resources:type_name -> CreateRecipeRequest.Resource
	30, // 3: CreateRecipeRequest.tags:type_name -> CreateRecipeRequest.Tag
	31, // 4: ListRecipeRequest.resources:type_name -> ListRecipeRequest.Resource
	32, // 5: ListRecipeRequest.tags:type_name -> ListRecipeRequest.Tag
	2,  // 6: ListRecipeResponse.recipes:type_name -> Recipe
	2,  // 7: FindRecipesByNameResponse.recipes:type_name -> Recipe
	2,  // 8: GetRecipeResponse.recipe:type_name -> Recipe
	2,  // 9: FindRecipesByTagsResponse.recipes:type_name -> Recipe
	5,  // 10: RecipeSvc.ListRecipe:input_type -> ListRecipeRequest
	7,  // 11: RecipeSvc.FindRecipesByName:input_type -> FindRecipesByNameRequest
	9,  // 12: RecipeSvc.GetRecipe:input_type -> GetRecipeRequest
	3,  // 13: RecipeSvc.CreateRecipe:input_type -> CreateRecipeRequest
	11, // 14: RecipeSvc.FindRecipesByTags:input_type -> FindRecipesByTagsRequest
	13, // 15: RecipeSvc.UpdateRecipeTitle:input_type -> UpdateRecipeTitleRequest
	15, // 16: RecipeSvc.UpdateRecipeDescription:input_type -> UpdateRecipeDescriptionRequest
	17, // 17: RecipeSvc.DeleteRecipe:input_type -> DeleteRecipeRequest
	0,  // 18: RecipeSvc.RemoveRecipeFromResource:input_type -> RemoveResourceFromRecipeRequest
	19, // 19: RecipeSvc.AddRecipeResource:input_type -> AddRecipeResourceRequest
	21, // 20: RecipeSvc.CreateTag:input_type -> CreateTagRequest
	23, // 21: RecipeSvc.AddTagToRecipe:input_type -> AddTagToRecipeRequest
	25, // 22: RecipeSvc.RemoveTagFromRecipe:input_type -> RemoveTagFromRecipeRequest
	6,  // 23: RecipeSvc.ListRecipe:output_type -> ListRecipeResponse
	8,  // 24: RecipeSvc.FindRecipesByName:output_type -> FindRecipesByNameResponse
	10, // 25: RecipeSvc.GetRecipe:output_type -> GetRecipeResponse
	4,  // 26: RecipeSvc.CreateRecipe:output_type -> CreateRecipeResponse
	12, // 27: RecipeSvc.FindRecipesByTags:output_type -> FindRecipesByTagsResponse
	14, // 28: RecipeSvc.UpdateRecipeTitle:output_type -> UpdateRecipeTitleResponse
	16, // 29: RecipeSvc.UpdateRecipeDescription:output_type -> UpdateRecipeDescriptionResponse
	18, // 30: RecipeSvc.DeleteRecipe:output_type -> DeleteRecipeResponse
	1,  // 31: RecipeSvc.RemoveRecipeFromResource:output_type -> RemoveRecipeFromResourceResponse
	20, // 32: RecipeSvc.AddRecipeResource:output_type -> AddRecipeResourceResponse
	22, // 33: RecipeSvc.CreateTag:output_type -> CreateTagResponse
	24, // 34: RecipeSvc.AddTagToRecipe:output_type -> AddTagToRecipeResponse
	26, // 35: RecipeSvc.RemoveTagFromRecipe:output_type -> RemoveTagFromRecipeResponse
	23, // [23:36] is the sub-list for method output_type
	10, // [10:23] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_ports_protos_srv_proto_init() }
func file_ports_protos_srv_proto_init() {
	if File_ports_protos_srv_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ports_protos_srv_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveResourceFromRecipeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ports_protos_srv_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveRecipeFromResourceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ports_protos_srv_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Recipe); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ports_protos_srv_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRecipeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ports_protos_srv_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRecipeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ports_protos_srv_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRecipeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ports_protos_srv_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRecipeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ports_protos_srv_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindRecipesByNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ports_protos_srv_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindRecipesByNameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ports_protos_srv_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRecipeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ports_protos_srv_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRecipeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ports_protos_srv_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindRecipesByTagsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ports_protos_srv_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindRecipesByTagsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ports_protos_srv_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRecipeTitleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ports_protos_srv_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRecipeTitleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ports_protos_srv_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRecipeDescriptionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ports_protos_srv_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRecipeDescriptionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ports_protos_srv_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRecipeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ports_protos_srv_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRecipeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ports_protos_srv_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRecipeResourceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ports_protos_srv_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRecipeResourceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ports_protos_srv_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTagRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ports_protos_srv_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTagResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ports_protos_srv_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddTagToRecipeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ports_protos_srv_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddTagToRecipeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ports_protos_srv_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveTagFromRecipeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ports_protos_srv_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveTagFromRecipeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ports_protos_srv_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Recipe_Resource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ports_protos_srv_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Recipe_Tag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ports_protos_srv_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRecipeRequest_Resource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ports_protos_srv_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRecipeRequest_Tag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ports_protos_srv_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRecipeRequest_Resource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ports_protos_srv_proto_msgTypes[32].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRecipeRequest_Tag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ports_protos_srv_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ports_protos_srv_proto_goTypes,
		DependencyIndexes: file_ports_protos_srv_proto_depIdxs,
		MessageInfos:      file_ports_protos_srv_proto_msgTypes,
	}.Build()
	File_ports_protos_srv_proto = out.File
	file_ports_protos_srv_proto_rawDesc = nil
	file_ports_protos_srv_proto_goTypes = nil
	file_ports_protos_srv_proto_depIdxs = nil
}
